### ISSUE TITLE
Problem loading sample dashboard 

### ISSUE THREAD

**Issue by Sputniza** [elastic/examples#53] opened 2016-09-27 16:36 UTC
Hello, I'm a newbie and got kibana and elasticsearch running.
I managed to ingest the data & do get a count response of approximately 473039

But I cannot complete the next step to load the dashboard. Folllowing this in Kibana:
Click the Settings tab >> Objects tab >> Import, and select restaurants_kibana.json

I do get:
Saved Objects: Cannot read property 'listeners' of undefined

Can someone help walk me through? What am I missing?

**Comment by asawariS** [comment] 2016-09-27 20:46
hi @Sputniza what version of Elasticsearch/Kibana are you running ?

**Comment by Sputniza** [comment] 2016-09-28 05:57
Sorry for not mentioning…
I’m running elastic 2.3.4
and Kibana 4.5.3

thank you,
anke

**Comment by Sputniza** [comment] 2016-09-28 06:30
Is it recommended to update to the current versions?

**Comment by Sputniza** [comment] 2016-10-08 11:26
@asawariS any ideas?
help really appreciated! Thank you. (sorry, forgot to ping you in my earlier answer)

**Comment by asawariS** [comment] 2016-10-11 18:27
sorry @Sputniza. didn't get to this earlier. I will look today

**Comment by asawariS** [comment] 2016-10-11 23:15
@Sputniza looks like this is related to https://github.com/elastic/kibana/issues/6789, and seem like there is no recommended fix. This might be a convoluted way to solve it -- but could you install Timelion by running this command in your Kibana install directory.

`./bin/kibana plugin -i elastic/timelion`

And then try re-importing the dashboard. Let me know if that works for you

**Comment by Sputniza** [comment] 2016-10-18 09:39
thank you @asawariS - followed your suggestion and installed timelion, then went step by step again through .. Visualize Data in Kibana as described for the sample. I did not receive the error above anymore, but my sample dashboard is empty: 
![image](https://cloud.githubusercontent.com/assets/10814907/19472336/2dab5bf4-9527-11e6-8cba-3523c1fc02e4.png)

the data availability check in terminal (curl) gives me the correct "count":473039,")
what else am I missing?
Thank you so much for your support -anke

**Comment by asawariS** [comment] 2016-10-18 15:25
Might be a timeframe thing (if you use snapshot / restore to add the data). Change the timeframe on the dashboards (upper right corner) to a larger period and see if that fixes it. @Sputniza

**Comment by tbragin** [comment] 2016-10-18 16:13
@Sputniza I reproduced your problem. It appears that the "Worst Restaurants" visualization relies on another 3rd party plugin, called Tagcloud: https://github.com/stormpython/tagcloud

You'll need to install that plugin per instructions in the link above, and re-run the import:
`bin/kibana plugin -i tagcloud -u https://github.com/stormpython/tagcloud/archive/master.zip`

@asawariS Could we make sure that this example (and others) detail which Kibana plugins need to be installed prior to running the dashboard import? 

On the Kibana side, we'll work on better error handling for this type of failure.

**Comment by tbragin** [comment] 2016-10-19 05:24
I went ahead and updated the readme of the NYC restaurant example to include instructions for installing the Tagcloud plugin.

**Comment by Sputniza** [comment] 2016-10-19 15:44
Thank you @tbragin! After installing the tagcloud I still didn't see any results. Finally changing the timeframe (from 6 month to 5 years) - as @asawariS  suggested - solved it! Unfortunately I cannot tell if both was necessary or not because I only tried this after I installed tagcloud. Thank you again!

**Comment by asawariS** [comment] 2016-10-19 15:48
Installing the Tag Cloud fixed the error message and middle visual in the dashboard with the warning icon. Changing the timeframe fixed the "no results found" part of the other empty visuals. Hope that helps. Closing this issue out. Feel free to ping open additional issues if you run into them.

**Closed by asawariS** 2016-10-19 15:48 UTC
Labels: docs

**Comment by tbragin** [comment] 2016-10-19 18:23
@Sputniza @asawariS I updated the readme in this example to tell the user to zoom out to the "Last 5 years" when they view the provided dashboard. The fact that the default dashboard time range is "Last 90 days" is unfortunate as it ages out pretty quickly.
